### ISSUE TITLE
Error when given a JOIN USING clause (uninitialized value in quotemeta)

### ISSUE THREAD

**Issue by ggaughan** [darold/pgFormatter#205]
Version 4.3 (Ubuntu 16.04.6)

````
Uncaught exception: Use of uninitialized value in quotemeta at /usr/local/share/perl/5.22.1/pgFormatter/Beautify.pm line 1350.
 at /usr/local/bin/pg_format line 19.
	main::__ANON__("Use of uninitialized value in quotemeta at /usr/local/share/p"...) called at /usr/local/share/perl/5.22.1/pgFormatter/Beautify.pm line 1350
	pgFormatter::Beautify::beautify(pgFormatter::Beautify=HASH(0x2314e58)) called at /usr/local/share/perl/5.22.1/pgFormatter/CLI.pm line 113
	pgFormatter::CLI::beautify(pgFormatter::CLI=HASH(0x210a108)) called at /usr/local/share/perl/5.22.1/pgFormatter/CLI.pm line 67
	pgFormatter::CLI::run(pgFormatter::CLI=HASH(0x210a108)) called at /usr/local/bin/pg_format line 49
````
with this file:

````
SELECT * FROM a JOIN b USING (c)
````

I suspect it's the ending on a `)` bit.

It does work if I add a semicolon at the end (though the online demo seems to work with or without a semicolon).

**Comment by darold** [comment]
Yes the issue with missing semi-colon at end of a statement have been fixed. The demo site http://sqlformat.darold.net/ is up-to-date with pgFormatter development code, that mean that if you can't reproduce the error or a formatting issue it has already been fixed in a recent commit. Feel free to download latest development code and override your installation.

**Comment by ggaughan** [comment]
Ah - I used the latest release. Rebuilding with master works - thanks.
