### ISSUE TITLE
unicode characters doesn't handled well in function

### ISSUE THREAD

**Issue by holymonson** [darold/pgFormatter#246]
Names with unicode character doesn't handled well in function variable.

```sql
-- doesn't work well
SELECT
    date_trunc('month', 日期) FROM table_;

-- works well 
SELECT
    date_trunc('month', date_)
FROM
    table_;
```

**Comment by darold** [comment]
pgFormatter function tokenize_sql() is not tokenizing this query correctly, it detects  `日期)` instead of two separate token. I guess it is worst with more complex queries. If you enclose the object name between double quote the tokenizer should work but at this time I have no evident solution for this problem that can be fixed in pgFormatter.
