### ISSUE TITLE
"user" word always converted to uppercase

### ISSUE THREAD

**Issue by lamualfa** [darold/pgFormatter#267]
> I have opened the issue before here, but the author asked me to moving the issue here. The issue: https://github.com/bradymholt/vscode-pgFormatter/issues/47.

## Problems

**Example when using `CREATE TABLE`**

```sql
CREATE TABLE IF NOT EXISTS user (
    id varchar(21) PRIMARY KEY
);
```

The `user` word will be converted be uppercase after formatting using this extension:

```sql
CREATE TABLE IF NOT EXISTS USER (
    id varchar(21) PRIMARY KEY
);
```

<hr/>

Example when using `REFERENCES user(id)` :

```sql
CREATE TABLE IF NOT EXISTS account (
    id varchar(21) PRIMARY KEY,
    identity TEXT NOT NULL,
    user_id varchar(21) FOREIGN KEY REFERENCES user(id),
    type account_types NOT NULL,
    provider account_providers,
    provider_data jsonb
);
```

The `user` word will be converted to uppercase after formatting using this extension:

```sql
CREATE TABLE IF NOT EXISTS account (
    id varchar(21) PRIMARY KEY,
    identity TEXT NOT NULL,
    user_id varchar(21) FOREIGN KEY REFERENCES USER (id),
    type account_types NOT NULL,
    provider account_providers,
    provider_data jsonb
);
```

## Screenshot

**Before**

![image](https://user-images.githubusercontent.com/39755201/143253370-7929f7fc-2f26-4872-9727-18168d63c70e.png)

**After**

![image](https://user-images.githubusercontent.com/39755201/143253441-3bff2319-a353-42eb-aceb-adec325b2038.png)

**Comment by polobo** [comment]
I feel there may be a problem here with PostgreSQL's behavior but at the end of the day the formatting is correct because "user" is a reserved keyword (like SELECT, UPDATE, etc...) which the formatter changes to all uppercase.  If you want to name something "user" you need to surround your name with double quotes.  The formatter should leave double quoted identifiers alone.  I'm unsure why PostgreSQL marks user as a keyword but then doesn't actually complain in places where it should.  However, that ship has sailed.  The programmer still needs to adhere to the rules surrounding the use of reserved keywords.

**Comment by darold** [comment]
I agree with @polobo, there is detection of reserved keywords in pgFormatter  and some false positive are also detected by looking at the previous and next keywords but this case is too generic.
