### ISSUE TITLE
Newline in parameter list

### ISSUE THREAD

**Issue by fab1an** [darold/pgFormatter#38]
* `CREATE TYPE jwt_token AS (token TEXT, field: TEXT);` is formatted to:

```sql
CREATE TYPE jwt_token
AS (
token TEXT,
    field: TEXT);
```

* `SELECT myFunction ('param1', 'param2') INTO myVariable`

```sql
SELECT
    myFunction ('param1',
        'param2') INTO myVariable
```

**Comment by darold** [comment]
Commit dd40c92 fixed the issue of CREATE TYPE format.

The other one is more complex to solve because pgFormatter doesn't  know if this is parameters of a function or parameters in a subselect. I have not solution about this right now, I leave this issue open so that anyone can see that this still has to be fixed.

Best regards

**Comment by fab1an** [comment]
Thanks for the fast reply!
